### ISSUE TITLE
Wrong Link: Integrations > Authentication Providers

### ISSUE THREAD

**Issue by tySwift93** [graphcool/content#102]
Starting from here: https://www.graph.cool/docs/reference/integrations/overview-seimeish6e/

The "Digits" link on the page, under the sub-heading "Authentication Providers", actually links to `https://www.graph.cool/docs/reference/integrations/algolia-emaig4uiki/` instead of the proper link, `https://www.graph.cool/docs/reference/integrations/digits-iaxohpee8o`.

**Comment by marktani** [comment]
Thanks for heads up!
