### ISSUE TITLE
Relevant Results Algolia Search

### ISSUE THREAD

**Issue by zach-is-my-name** [graphcool/content#116]
I'm not sure how Algolia is supposed to work, but from top level Docs (https://www.graph.cool/docs/) I query 'Relations' (because I want to learn about Relations) and I'm returned only one result, 'How to Store Meta Information for Relations', I feel like I should have gotten back at least the sub-section on Relations within the Schema section,  called 'Relations'
 https://www.graph.cool/docs/reference/schema/relations-goh5uthoc1/

Summary: I want '/docs/Relations' 
I query: 'Relations'
I only get back: /docs/graphql-meta-information-for-relations

**Comment by marktani** [comment]
Thanks! I need to look into this soon, related #115

**Comment by marktani** [comment]
Hey @zach-is-my-name can you try some example search queries again?

**Comment by marktani** [comment]
I improved the search results from Algolia significantly. `Relations` still does not return the relations article though, because there are too many other relevant articles 😆 

![image](https://user-images.githubusercontent.com/1780597/27261526-ecb1bb60-5444-11e7-8d2f-1561cefc0a0f.png)

**Comment by zach-is-my-name** [comment]
Hah! 

Very Helpful! 👍
