### ISSUE TITLE
Broken images in docs

### ISSUE THREAD

**Issue by klikstermkd** [graphcool/content#133]
The image in the [Data Browser](https://www.graph.cool/docs/reference/console/data-browser-och3ookaeb/) page in the Docs is broken.

Although, here on Github it loads fine. https://github.com/graphcool/content/blob/dev/content/reference/console/data-view/data-browser.md

Also, on [Playground](https://www.graph.cool/docs/reference/console/playground-oe1ier4iej/) they are not displaying as well.

**Comment by marktani** [comment]
Thanks for bringing this up, it has been fixed :)
