### ISSUE TITLE
Angular Quickstart is broken

### ISSUE THREAD

**Issue by marktani** [graphcool/content#156]
https://github.com/graphcool-examples/angular-graphql/issues/3

**Comment by kbrandwijk** [comment]
Filenames starting with . are hidden files on Linux. If they are not shown, they also don't end up in the zip :) I think it's a stupid change in angular-cli, because a lot of people on Linux are complaining that they lost the file while copying a folder...

**Comment by schickling** [comment]
Thanks a lot for this great hint @kbrandwijk! We've fixed it!
