### ISSUE TITLE
Download link broken on File Management

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/content#159]
https://www.graph.cool/docs/reference/file-handling/overview-eer4wiang0/#uploading-a-file-with-plain-http

**Comment by marktani** [comment]
I reworked the file handling chapter in the docs and now [there's a dedicated example section](https://www.graph.cool/docs/reference/file-handling/file-upload-examples-zaif4eing1/).

**Comment by kbrandwijk** [comment]
May I suggest a link to a certain example project? ;)
