### ISSUE TITLE
Mention in documentation that ES6 is available for inline functions

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/content#178]
With the 'use latest' line, webtask (and therefore inline functions) support ES6. The documentation does not mention that.

```js
"use latest"

// Click "EXAMPLE EVENT" to see whats in `event`
export default (event) => {
  console.log(event.context)
  return { data: event.data }
}
```

**Comment by marktani** [comment]
https://www.graph.cool/docs/reference/functions/environment-hohl0iy1ji/#node-runtime
