### ISSUE TITLE
Interactive Cheatsheet for generated API

### ISSUE THREAD

**Issue by marktani** [graphcool/content#18]
> user types in the name of the entity, lets say for example, `Widget`. gets back a description of the graph that’s created from it, plus the singular and plural representations along with Id (widgetId) required for edges etc.

**Comment by marktani** [comment]
Here's a non-interactive cheatsheet for now :slightly_smiling_face: 

https://www.graph.cool/docs/faq/simple-api-cheatsheet-aigheequ7j/

**Comment by marktani** [comment]
Let's stick with the non-interactive version 😛

**Comment by kbrandwijk** [comment]
Maybe add a reference to https://github.com/2fd/graphdoc for creating your own endpoint documentation somewhere.
