### ISSUE TITLE
Issues / Suggestions for relay-modern-getting-started

### ISSUE THREAD

**Issue by claym** [graphcool/content#207]
- would be good to notify the user they will get errors when they start adding fragments. the project recompiles automagically, so you immediately get errors and it makes you think you did something wrong
- running on windows, relay-compiler doesn't attach to the path after install, may be confusing for those users. running ./node_modules/relay-compiler/bin/relay-compiler works fine
- the default "playground" for me was "simple", and the mutations didn't work there. had to change to relay for the snippets to process
- there's something going on when copying large sections of code. If it's a large chunk of code (like for DeletePostMutation.js) instead of copying the text, it just copies "-" (no quotes). If you break it up, and copy it in parts, it works fine. Running Chrome  59.0.3071.115 on Windows 10

**Comment by nikolasburk** [comment]
Thanks a lot @claym, these are great suggestions! I updated the tutorial and added a note about the errors in the relay-compiler as well as an additional instruction to switch the Playground mode from Simple to Relay before running the mutations. Thanks again! 🙌
