### ISSUE TITLE
Describe relations filters in filtering section

### ISSUE THREAD

**Issue by JensMadsen** [graphcool/content#295]
no description here https://www.graph.cool/docs/reference/simple-api/filtering-by-field-xookaexai0/

**Comment by marktani** [comment]
What do you mean? There's a section called "Relation filters": https://www.graph.cool/docs/reference/simple-api/filtering-by-field-xookaexai0/#relation-filters

**Comment by JensMadsen** [comment]
Sorry. Very stupid from my side:-) I just ment that the relations filters did not appear in the list at the bottom of  the page
