### ISSUE TITLE
iechu0shia: Relay supports custom queries and mutations

### ISSUE THREAD

**Issue by nodkz** [graphcool/content#33]
In this article https://www.graph.cool/docs/tutorials/relay-vs-apollo-iechu0shia/ written that Relay can fetch data in one way via Relay.Container. It's incorrect, you may fetch it manually, eg https://github.com/nodkz/relay-northwind-app/blob/master/app/components/orders/ToggleOrder.js#L29-L44

It has ugly API, but can be simplified for your needs, eg. with creating `fetch` and `mutate` methods for  https://github.com/nodkz/relay-northwind-app/blob/master/app/relay2Store.js Tge diff can be found here, to compare how code becomes more beautiful https://github.com/nodkz/relay-northwind-app/pull/3/files#diff-b65e2250ac0c9ac294c5d11c75f510ba

Also can be improved mutations, more info here https://github.com/facebook/relay/issues/1046#issuecomment-272358621

**Comment by bidanjun** [comment]
i think,what they talk is about relay2,that just published. so your northwnd sample should be changed now...

**Comment by nodkz** [comment]
@bidanjun nope, this great article compares apollo-client with Relay1.

Relay2 has for now small amount of docs. I suppose that need​ to spend several weeks/months for obtaining enough experience for writing such comparison with Relay2.

**Comment by nikolasburk** [comment]
thanks @nodkz! it's fixed and will be deployed with our next merge to master 👍
