### ISSUE TITLE
graphql-tag now with react-apollo

### ISSUE THREAD

**Issue by joaobsantos** [graphcool/content#40]
Now you can use, import { graphql, gql } from 'react-apollo'.
There's no need to install graphql-tag dependency.

**Old way:**
import { graphql } from 'react-apollo'
import { gql } from 'graphql-tag'

**New way:**
import { graphql, gql } from 'react-apollo'

**Comment by schickling** [comment]
@marktani can you go through all resources where we've used `graphql-tag` and remove it?

**Comment by marktani** [comment]
removed as duplicate of #56
