### ISSUE TITLE
[Meta] Migrations

### ISSUE THREAD

**Issue by marktani** [graphcool/content#42]
* [x] new chapter in Console
* [x] migration value for changing a field to `required` only overwrites `null` values. unless it's a list field, then it overwrites everything.

**Comment by do4gr** [comment]
This is the behavior when the updateFieldMutation changes the type

opt -> if you provide migValue we will use it on all fields
req -> you have to provide migValue when nodes are present, we will use it on all fields
ign -> you can provide a migValue but we will ignore it

| from/to  | String | Int | Float | Boolean | Enum | DateTime |
|----------|--------|-----|-------|---------|------|----------|
| String   | ign    | req | req   | req     | req  | req      |
| Int      | opt    | ign | req   | req     | req  | req      |
| Float    | opt    | req | ign   | req     | req  | req      |
| Boolean  | opt    | req | req   | ign     | req  | req      |
| Enum     | opt    | req | req   | req     | ign  | req      |
| DateTime | opt    | req | req   | req     | req  | ign      |
