### ISSUE TITLE
Freecom Part 2

### ISSUE THREAD

**Issue by marktani** [graphcool/content#49]
> i found out that the code provided for creating the NetworkInterface along with the ApolloClient: import { ApolloClient, createNetworkInterface } from 'react-apollo'

> seems to be importing from the wrong library. It belief it should be from "apollo-client" not "react-apollo"

> I'm especially interested in the GraphCool + stdlib integration and seeing how that is done in a secure way

**Comment by Musbell** [comment]
The video tutorial for week 2 is different from what is on the article. which one am i to follow?

**Comment by Musbell** [comment]
Mistake:
mutation createMessage($text: String!, conversationId: ID!) {
    ...
  }

instead:
 mutation createMessage($text: String!, $conversationId: ID!){
  ...
}

**Comment by Musbell** [comment]
Mistake:
 allMessages(filter: {
      conversationId: $conversationId
    }) {
     ...
    }

instead: 
allMessages(filter: {
      conversation: {
        id: $conversationId
      }
    }){
...
}

**Comment by nikolasburk** [comment]
Thanks @Musbell for pointing out the errors, they're fixed and will be published the next time we merge our docs into master! 

Btw, if you want to code along in the Freecom tutorial, you should indeed follow the videos - the written tutorials only give a conceptual overview of the current topic and thus might deviate from the actual implementation.
