### ISSUE TITLE
daisheeb9x: Relations article + video are outdated

### ISSUE THREAD

**Issue by marktani** [graphcool/content#52]

**Comment by nikolasburk** [comment]
just to be sure, what resources does this refer to exactly?

probably this one?! https://www.graph.cool/docs/tutorials/quickstart-2-daisheeb9x/

**Comment by marktani** [comment]
Yep!

**Comment by marktani** [comment]
The video is here https://www.youtube.com/watch?v=Pz51CTyqSLo

**Comment by marktani** [comment]
also remove `thaeghi8ro`
