### ISSUE TITLE
"slackChannelIndex" is not included on "type Conversation" in freecom.schema file

### ISSUE THREAD

**Issue by Musbell** [graphcool/content#58]
I want to bring into notice that "slackChannelIndex" is not included on "type Conversation" in freecom.schema file; 

type Conversation {
createdAt: DateTime
customer: Customer @relation(name: "ConversationsFromCustomer")
id: ID!
messages: [Message!]! @relation(name: "MessagesInConversation")
slackChannelName: String
updatedAt: DateTime
}

therefore, when i tried to query for it, i am receiving this error: "Cannot query field 'slackChannelIndex' on type 'Conversation'. Did you mean 'slackChannelName'?"

**Comment by Musbell** [comment]
Agent relation not created on "type Conversation"

**Comment by Musbell** [comment]
no imageUrl field on "type Agent"

**Comment by nikolasburk** [comment]
thanks, this is fixed now. the schema that was contained in the starter project was slightly outdated and thus had `slackChannelName` as wrong property (`slackChannelIndex` is the right one). to fix it, you can do either of two things:

- update the existing fields in the [console UI](https://console.graph.cool)
- create a new project based on the new correct schema
