### ISSUE TITLE
Upload file with RN imagepicker

### ISSUE THREAD

**Issue by marktani** [graphcool/content#90]
```js
export const uploadPhoto = (localUri, filename) => {
  const formData = new FormData()
  const data = {
    uri: localUri,
    name: `${filename}.jpg`,
    type: 'image/jpeg',
  }

  formData.append('data', data)

  const options = {
    method: 'POST',
    body: formData,
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'multipart/form-data',
    },
  }

  return fetch(FILE_ENDPOINT, options)
  .then((response) => {
    return response.json()
  }).then((image) => {
    console.log(image)
    return image
  })
  .catch(error => console.error(`Error uploading image))
}
```

**Comment by michaelspeed** [comment]
This worked great. Thanx
You guys should make an api out of it .. with variables like $endpoints, $filename, $type, $uri

**Comment by marktani** [comment]
Do you mean a client-side library?

**Comment by michaelspeed** [comment]
ya a client side library! with also be good if we can add mutations and querys

**Comment by michaelspeed** [comment]
I am getting this error while uploading  - `In this environment the sources for assign MUST be an object.This error is a performance optimization and not spec compliant.`

the function looks like this - [https://gist.github.com/michaelspeed/2cdbfbbba3622aa4f97ccbc1ac18e9f7](https://gist.github.com/michaelspeed/2cdbfbbba3622aa4f97ccbc1ac18e9f7)

**Comment by Alex-Mann** [comment]
Is there a reason that the data form object fails to upload when more object properties (other than uri, name, and type) are added?

**Comment by ajmakhl** [comment]
When I try to run this code.  I get this error.
<img width="474" alt="screen shot 2017-06-19 at 3 40 44 pm" src="https://user-images.githubusercontent.com/17507288/27302604-b49044e2-5505-11e7-8e3c-099186a1df22.png">
localUri and filename came from RN image picker response.uri and response.filename which looks like this...
response.uri{ /Users/-USER-/Library/Developer/CoreSimulator/Devices/D569DFF8-AA9E-4A7C-9... }
response.filename{ IMG_0002.JPG }
```
  UploadPhoto = (localUri, filename) => {
    const formData = new FormData()
    const data = {
      uri: `${localUri}`,
      name: `${filename}.jpg`,
      type: 'image/jpeg'
    }
    formData.append('data', data)
    const options = {
      method: 'POST',
      body: formData,
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'multipart/form-data'
      }
    }
    const FILE_ENDPOINT = 'https://api.graph.cool/file/v1/cj3......';
    return fetch(FILE_ENDPOINT, options)
    .then((response) => {
      return response.json()
    })
    .then((image) => {
      return image
      console.log(image)
    })
    .catch(error => console.error(`Error uploading image`, error))
  }
```

**Comment by michaelspeed** [comment]
this method does not work for files and videos. can you give me example to upload videos and files with react native ?

**Comment by roycclu** [comment]
@marktani hi I followed the example exactly, but am getting this 500 internal server error:

`
headers:Headers
ok:false
status:500
statusText:"Internal Server Error"
type:"default"
url:"https://api.graph.cool/file/v1/cj52jh14jpyjc0196fj1nvai6"
_bodyInit:""
_bodyText:""
`

Any idea why?

**Comment by joefazz** [comment]
Hi, I just made a PR about this. You need to make sure you define the File type with all the required fields in your schema otherwise you will only get 500 responses.

**Comment by roycclu** [comment]
@joefazz Can you give an example of this? If you use it with RN, can you post your upload code?

**Comment by joefazz** [comment]
It's not about the upload code it's about the actual schema, put a type into it that looks like this:
`type File @model {
    contentType: String!
    createdAt: DateTime!
    id: ID! @isUnique
    name: String!
    secret: String! @isUnique
    size: Int!
    updatedAt: DateTime!
    url: String! @isUnique
}`
and it should start working (after you deploy).

By the way you included your DB id in the initial comment you made. Should probably remove it otherwise someone could bombard it with files and use up all your storage.

**Comment by roycclu** [comment]
@joefazz thanks for the heads up. 

I'm using apollo-client with graphcool console. So no need to define schema on client.
Does your upload code look something like this?
`
    let formData = new FormData();
    const data = {
      uri: file.uri,
      encoding: 'utf8',
      name: `${file.filename}`,
      fileName: `${file.filename}`,
      type: 'image/jpeg',
    };
    formData.append('data', data);

      const file = await fetch(
        'https://api.graph.cool/file/v1/<key>',
        {
          method: 'POST',
          body: formData,
          headers: {
            Accept: 'application/json',
            'Content-Type': 'multipart/form-data',
          },
        },
      );
`

I'm following the example really closely here, but still get a 500 internal server error and "Error from cloudfront message". Maybe something wrong in the header? @marktani

**Comment by joefazz** [comment]
I'm also using graphcool with apollo client. If you're using graphcool version 0.x then you need to find your types.graphql file or go into the graphcool console and add that File type that I mentioned above, your fetch is correctly structured but will never resolve unless you add a File type.

Also I'm not sure encoding is a valid property in your formData but I'm not very familiar with formData. Same with fileName (name property will be the filename in your DB)

**Comment by roycclu** [comment]
File is a system type defined in my graphcool console. So that's no problem. I've also uploaded files successfully using 'request' with node. 

But still getting this 500 error:

<img width="729" alt="screen shot 2018-01-17 at 10 27 18 pm" src="https://user-images.githubusercontent.com/16176418/35047742-cb9044ae-fbd5-11e7-9064-5fc7b188883a.png">
@marktani would you be able to chime in on this?
Couldn't the internal server error be more descriptive of what went wrong?

**Comment by roycclu** [comment]
Solved it. Used 'react-native-fetch-blob' and it worked. 
Code as follows:
      const res = await RNFetchBlob.fetch(
        'POST',
        configs.fileApi,
        {
          Accept: 'application/json',
          'Content-Type': 'multipart/form-data',
        },
        [
          {
            name: 'data',
            filename: 'test' + '.jpg',
            type: 'image/jpeg',
            data: RNFetchBlob.wrap(file.origURL),
          },
        ],
      );

**Comment by vendicto** [comment]
@roycclu Thanks man! I don't know why, but in this case:
`const formData = new FormData()
        const data = {
            uri: file.uri,
            name: `test.jpg`,
            type: 'image/jpeg',
        }
        formData.append('data', data)
        const options = {
            method: 'POST',
            body: formData,
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'multipart/form-data',
                'authorization': `Bearer ${token}`,
            },
        }
        return fetch(file_api, options)
            .then((response) => {
                console.log('response.json() ', response.json())
                return response.json()
            }).then((image) => {
                console.log('image ', image)
                return image
            })
            .catch(error => console.error(`Error uploading image`, error))`
I have 500 error:
"Failed to load https://api.graph.cool/file/v1/xxx: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8081' is therefore not allowed access. The response had HTTP status code 500."
And in the body I have a string [Object object] (that was strange for me)
