### ISSUE TITLE
axios-file upload

### ISSUE THREAD

**Issue by marktani** [graphcool/content#95]
```js
onFileUpload: function (files) {
  this.file = files[0]
  let data = new FormData()
  data.append('data', files[0])
  axios.post('https://api.graph.cool/file/v1/__PROJECT_ID__', data, {
    headers: {
      'Content-Type': 'multipart/form-data',
    }
  }).then(response => {
    console.log('file upload response',response)
  })
}
```

**Comment by janpauldahlke** [comment]
is this example working for the new graphcool, baas? i cannot make it work from my project into a localinstance of graphcool. always recivieving the error 
`POST http://localhost:60000/simple/v1/cjgxei1ta00040149ajdwk6ek 415 (Unsupported Media Type)`
`dokumentenupload:1 Failed to load http://localhost:60000/simple/v1/cjgxei1ta00040149ajdwk6ek: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 415.`
